# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kalorianaliz.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kalorianaliz.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12kalorianaliz.proto\x12\x0ckalorianaliz\"I\n\x0ePredictRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x12\n\ntext_input\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"\x87\x01\n\x0fPredictResponse\x12\x11\n\tfood_name\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x10\n\x08\x63\x61lories\x18\x03 \x01(\x02\x12\x13\n\x0bgradcam_b64\x18\x04 \x01(\t\x12\x16\n\x0elow_confidence\x18\x05 \x01(\x08\x12\x0e\n\x06source\x18\x06 \x01(\t2X\n\x0e\x43\x61lorieService\x12\x46\n\x07Predict\x12\x1c.kalorianaliz.PredictRequest\x1a\x1d.kalorianaliz.PredictResponseB\x14\xaa\x02\x11KaloriAnaliz.Grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kalorianaliz_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021KaloriAnaliz.Grpc'
  _globals['_PREDICTREQUEST']._serialized_start=36
  _globals['_PREDICTREQUEST']._serialized_end=109
  _globals['_PREDICTRESPONSE']._serialized_start=112
  _globals['_PREDICTRESPONSE']._serialized_end=247
  _globals['_CALORIESERVICE']._serialized_start=249
  _globals['_CALORIESERVICE']._serialized_end=337
# @@protoc_insertion_point(module_scope)
